<?php
/**
 * AnalyticsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * AnalyticsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AnalyticsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'analyticsCustomerReport' => [
            'application/json',
        ],
        'analyticsProductReport' => [
            'application/json',
        ],
        'analyticsReport' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation analyticsCustomerReport
     *
     * analytics.customer_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $customer_type Filter analytics customers by customer type (optional)
     * @param  string|null $email Filter analytics customers by email (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'total_spend')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsCustomerReport'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult
     */
    public function analyticsCustomerReport($date_from = null, $date_to = null, $count = 10, $currency_id = null, $store_id = null, $customer_type = null, $email = null, $sort_by = 'total_spend', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsCustomerReport'][0])
    {
        list($response) = $this->analyticsCustomerReportWithHttpInfo($date_from, $date_to, $count, $currency_id, $store_id, $customer_type, $email, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType);
        return $response;
    }

    /**
     * Operation analyticsCustomerReportWithHttpInfo
     *
     * analytics.customer_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $customer_type Filter analytics customers by customer type (optional)
     * @param  string|null $email Filter analytics customers by email (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'total_spend')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsCustomerReport'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function analyticsCustomerReportWithHttpInfo($date_from = null, $date_to = null, $count = 10, $currency_id = null, $store_id = null, $customer_type = null, $email = null, $sort_by = 'total_spend', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsCustomerReport'][0])
    {
        $request = $this->analyticsCustomerReportRequest($date_from, $date_to, $count, $currency_id, $store_id, $customer_type, $email, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation analyticsCustomerReportAsync
     *
     * analytics.customer_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $customer_type Filter analytics customers by customer type (optional)
     * @param  string|null $email Filter analytics customers by email (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'total_spend')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsCustomerReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function analyticsCustomerReportAsync($date_from = null, $date_to = null, $count = 10, $currency_id = null, $store_id = null, $customer_type = null, $email = null, $sort_by = 'total_spend', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsCustomerReport'][0])
    {
        return $this->analyticsCustomerReportAsyncWithHttpInfo($date_from, $date_to, $count, $currency_id, $store_id, $customer_type, $email, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation analyticsCustomerReportAsyncWithHttpInfo
     *
     * analytics.customer_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $customer_type Filter analytics customers by customer type (optional)
     * @param  string|null $email Filter analytics customers by email (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'total_spend')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsCustomerReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function analyticsCustomerReportAsyncWithHttpInfo($date_from = null, $date_to = null, $count = 10, $currency_id = null, $store_id = null, $customer_type = null, $email = null, $sort_by = 'total_spend', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsCustomerReport'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ResponseAnalyticsCustomerReportResult';
        $request = $this->analyticsCustomerReportRequest($date_from, $date_to, $count, $currency_id, $store_id, $customer_type, $email, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'analyticsCustomerReport'
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $customer_type Filter analytics customers by customer type (optional)
     * @param  string|null $email Filter analytics customers by email (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'total_spend')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsCustomerReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function analyticsCustomerReportRequest($date_from = null, $date_to = null, $count = 10, $currency_id = null, $store_id = null, $customer_type = null, $email = null, $sort_by = 'total_spend', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsCustomerReport'][0])
    {













        $resourcePath = '/analytics.customer_report.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_from,
            'date_from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'date_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $count,
            'count', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency_id,
            'currency_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $store_id,
            'store_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customer_type,
            'customer_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $email,
            'email', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_direction,
            'sort_direction', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_cursor,
            'page_cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_fields,
            'response_fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-store-key');
        if ($apiKey !== null) {
            $headers['x-store-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation analyticsProductReport
     *
     * analytics.product_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $product_ids Filter analytics by product ids (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $categories_ids Defines product add that is specified by comma-separated categories id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'items_sold')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsProductReport'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ResponseAnalyticsProductReportResult
     */
    public function analyticsProductReport($date_from = null, $date_to = null, $count = 10, $product_ids = null, $currency_id = null, $store_id = null, $categories_ids = null, $sort_by = 'items_sold', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsProductReport'][0])
    {
        list($response) = $this->analyticsProductReportWithHttpInfo($date_from, $date_to, $count, $product_ids, $currency_id, $store_id, $categories_ids, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType);
        return $response;
    }

    /**
     * Operation analyticsProductReportWithHttpInfo
     *
     * analytics.product_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $product_ids Filter analytics by product ids (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $categories_ids Defines product add that is specified by comma-separated categories id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'items_sold')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsProductReport'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ResponseAnalyticsProductReportResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function analyticsProductReportWithHttpInfo($date_from = null, $date_to = null, $count = 10, $product_ids = null, $currency_id = null, $store_id = null, $categories_ids = null, $sort_by = 'items_sold', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsProductReport'][0])
    {
        $request = $this->analyticsProductReportRequest($date_from, $date_to, $count, $product_ids, $currency_id, $store_id, $categories_ids, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ResponseAnalyticsProductReportResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ResponseAnalyticsProductReportResult' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ResponseAnalyticsProductReportResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ResponseAnalyticsProductReportResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseAnalyticsProductReportResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation analyticsProductReportAsync
     *
     * analytics.product_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $product_ids Filter analytics by product ids (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $categories_ids Defines product add that is specified by comma-separated categories id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'items_sold')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsProductReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function analyticsProductReportAsync($date_from = null, $date_to = null, $count = 10, $product_ids = null, $currency_id = null, $store_id = null, $categories_ids = null, $sort_by = 'items_sold', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsProductReport'][0])
    {
        return $this->analyticsProductReportAsyncWithHttpInfo($date_from, $date_to, $count, $product_ids, $currency_id, $store_id, $categories_ids, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation analyticsProductReportAsyncWithHttpInfo
     *
     * analytics.product_report
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $product_ids Filter analytics by product ids (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $categories_ids Defines product add that is specified by comma-separated categories id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'items_sold')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsProductReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function analyticsProductReportAsyncWithHttpInfo($date_from = null, $date_to = null, $count = 10, $product_ids = null, $currency_id = null, $store_id = null, $categories_ids = null, $sort_by = 'items_sold', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsProductReport'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ResponseAnalyticsProductReportResult';
        $request = $this->analyticsProductReportRequest($date_from, $date_to, $count, $product_ids, $currency_id, $store_id, $categories_ids, $sort_by, $sort_direction, $page_cursor, $response_fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'analyticsProductReport'
     *
     * @param  string|null $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  int|null $count This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     * @param  string|null $product_ids Filter analytics by product ids (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $categories_ids Defines product add that is specified by comma-separated categories id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'items_sold')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'desc')
     * @param  string|null $page_cursor Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsProductReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function analyticsProductReportRequest($date_from = null, $date_to = null, $count = 10, $product_ids = null, $currency_id = null, $store_id = null, $categories_ids = null, $sort_by = 'items_sold', $sort_direction = 'desc', $page_cursor = null, $response_fields = null, string $contentType = self::contentTypes['analyticsProductReport'][0])
    {













        $resourcePath = '/analytics.product_report.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_from,
            'date_from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'date_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $count,
            'count', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $product_ids,
            'product_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency_id,
            'currency_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $store_id,
            'store_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $categories_ids,
            'categories_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_direction,
            'sort_direction', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_cursor,
            'page_cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_fields,
            'response_fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-store-key');
        if ($apiKey !== null) {
            $headers['x-store-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation analyticsReport
     *
     * analytics.report
     *
     * @param  string $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (required)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  string|null $interval Interval for analytics report breakdown (optional)
     * @param  string|null $order_status Retrieves orders specified by order status (optional)
     * @param  string|null $financial_status Retrieves orders specified by financial status (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'date')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'asc')
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsReport'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ResponseAnalyticsReportResult
     */
    public function analyticsReport($date_from, $date_to = null, $interval = null, $order_status = null, $financial_status = null, $currency_id = null, $store_id = null, $sort_by = 'date', $sort_direction = 'asc', $response_fields = null, string $contentType = self::contentTypes['analyticsReport'][0])
    {
        list($response) = $this->analyticsReportWithHttpInfo($date_from, $date_to, $interval, $order_status, $financial_status, $currency_id, $store_id, $sort_by, $sort_direction, $response_fields, $contentType);
        return $response;
    }

    /**
     * Operation analyticsReportWithHttpInfo
     *
     * analytics.report
     *
     * @param  string $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (required)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  string|null $interval Interval for analytics report breakdown (optional)
     * @param  string|null $order_status Retrieves orders specified by order status (optional)
     * @param  string|null $financial_status Retrieves orders specified by financial status (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'date')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'asc')
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsReport'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ResponseAnalyticsReportResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function analyticsReportWithHttpInfo($date_from, $date_to = null, $interval = null, $order_status = null, $financial_status = null, $currency_id = null, $store_id = null, $sort_by = 'date', $sort_direction = 'asc', $response_fields = null, string $contentType = self::contentTypes['analyticsReport'][0])
    {
        $request = $this->analyticsReportRequest($date_from, $date_to, $interval, $order_status, $financial_status, $currency_id, $store_id, $sort_by, $sort_direction, $response_fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ResponseAnalyticsReportResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ResponseAnalyticsReportResult' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ResponseAnalyticsReportResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ResponseAnalyticsReportResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ResponseAnalyticsReportResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation analyticsReportAsync
     *
     * analytics.report
     *
     * @param  string $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (required)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  string|null $interval Interval for analytics report breakdown (optional)
     * @param  string|null $order_status Retrieves orders specified by order status (optional)
     * @param  string|null $financial_status Retrieves orders specified by financial status (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'date')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'asc')
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function analyticsReportAsync($date_from, $date_to = null, $interval = null, $order_status = null, $financial_status = null, $currency_id = null, $store_id = null, $sort_by = 'date', $sort_direction = 'asc', $response_fields = null, string $contentType = self::contentTypes['analyticsReport'][0])
    {
        return $this->analyticsReportAsyncWithHttpInfo($date_from, $date_to, $interval, $order_status, $financial_status, $currency_id, $store_id, $sort_by, $sort_direction, $response_fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation analyticsReportAsyncWithHttpInfo
     *
     * analytics.report
     *
     * @param  string $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (required)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  string|null $interval Interval for analytics report breakdown (optional)
     * @param  string|null $order_status Retrieves orders specified by order status (optional)
     * @param  string|null $financial_status Retrieves orders specified by financial status (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'date')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'asc')
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function analyticsReportAsyncWithHttpInfo($date_from, $date_to = null, $interval = null, $order_status = null, $financial_status = null, $currency_id = null, $store_id = null, $sort_by = 'date', $sort_direction = 'asc', $response_fields = null, string $contentType = self::contentTypes['analyticsReport'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ResponseAnalyticsReportResult';
        $request = $this->analyticsReportRequest($date_from, $date_to, $interval, $order_status, $financial_status, $currency_id, $store_id, $sort_by, $sort_direction, $response_fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'analyticsReport'
     *
     * @param  string $date_from Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (required)
     * @param  string|null $date_to End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     * @param  string|null $interval Interval for analytics report breakdown (optional)
     * @param  string|null $order_status Retrieves orders specified by order status (optional)
     * @param  string|null $financial_status Retrieves orders specified by financial status (optional)
     * @param  string|null $currency_id Currency Id (optional)
     * @param  string|null $store_id Store Id (optional)
     * @param  string|null $sort_by Set field to sort by (optional, default to 'date')
     * @param  string|null $sort_direction Set sorting direction (optional, default to 'asc')
     * @param  string|null $response_fields Set this parameter to choose which entity fields to retrieve. Use comma-separated field names in curly braces, nested to match the response structure, e.g. {result{product{id,name}}}. The wildcard * returns every field at a level: {*} gives the whole response, {result{product{*}}} all product fields. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['analyticsReport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function analyticsReportRequest($date_from, $date_to = null, $interval = null, $order_status = null, $financial_status = null, $currency_id = null, $store_id = null, $sort_by = 'date', $sort_direction = 'asc', $response_fields = null, string $contentType = self::contentTypes['analyticsReport'][0])
    {

        // verify the required parameter 'date_from' is set
        if ($date_from === null || (is_array($date_from) && count($date_from) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $date_from when calling analyticsReport'
            );
        }











        $resourcePath = '/analytics.report.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_from,
            'date_from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'date_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $interval,
            'interval', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_status,
            'order_status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $financial_status,
            'financial_status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency_id,
            'currency_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $store_id,
            'store_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_direction,
            'sort_direction', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_fields,
            'response_fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-store-key');
        if ($apiKey !== null) {
            $headers['x-store-key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
