<?php
/**
 * ProductAddBatchPayloadInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API2Cart OpenAPI
 *
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProductAddBatchPayloadInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProductAddBatchPayloadInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProductAddBatch_payload_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'description' => 'string',
        'short_description' => 'string',
        'sku' => 'string',
        'model' => 'string',
        'asin' => 'string',
        'upc' => 'string',
        'ean' => 'string',
        'gtin' => 'string',
        'mpn' => 'string',
        'barcode' => 'string',
        'price' => 'float',
        'old_price' => 'float',
        'cost_price' => 'float',
        'special_price' => 'float',
        'sprice_create' => 'string',
        'sprice_expire' => 'string',
        'advanced_prices' => '\OpenAPI\Client\Model\ProductAddBatchPayloadInnerAdvancedPricesInner[]',
        'fixed_cost_shipping_price' => 'float',
        'quantity' => 'float',
        'manage_stock' => 'bool',
        'product_type' => 'string',
        'marketplace_item_properties' => 'object',
        'is_free_shipping' => 'bool',
        'taxable' => 'bool',
        'status' => 'string',
        'condition' => 'string',
        'visible' => 'string',
        'available_for_view' => 'bool',
        'available_for_sale' => 'bool',
        'is_virtual' => 'bool',
        'in_stock' => 'bool',
        'type' => 'string',
        'downloadable' => 'bool',
        'weight' => 'float',
        'length' => 'float',
        'width' => 'float',
        'height' => 'float',
        'weight_unit' => 'string',
        'dimensions_unit' => 'string',
        'store_id' => 'string',
        'lang_id' => 'string',
        'category_id' => 'string',
        'warehouse_id' => 'string',
        'categories_ids' => 'string[]',
        'related_products_ids' => 'string[]',
        'up_sell_products_ids' => 'string[]',
        'cross_sell_products_ids' => 'string[]',
        'stores_ids' => 'string[]',
        'tax_class_id' => 'string',
        'meta_title' => 'string',
        'meta_description' => 'string',
        'meta_keywords' => 'string[]',
        'search_keywords' => 'string[]',
        'harmonized_system_code' => 'string',
        'url' => 'string',
        'seo_url' => 'string',
        'manufacturer' => 'string',
        'manufacturer_id' => 'string',
        'backorder_status' => 'string',
        'images' => '\OpenAPI\Client\Model\ProductAddBatchPayloadInnerImagesInner[]',
        'tags' => 'string[]',
        'files' => '\OpenAPI\Client\Model\ProductAddFilesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'description' => null,
        'short_description' => null,
        'sku' => null,
        'model' => null,
        'asin' => null,
        'upc' => null,
        'ean' => null,
        'gtin' => null,
        'mpn' => null,
        'barcode' => null,
        'price' => null,
        'old_price' => null,
        'cost_price' => null,
        'special_price' => null,
        'sprice_create' => null,
        'sprice_expire' => null,
        'advanced_prices' => null,
        'fixed_cost_shipping_price' => null,
        'quantity' => null,
        'manage_stock' => null,
        'product_type' => null,
        'marketplace_item_properties' => null,
        'is_free_shipping' => null,
        'taxable' => null,
        'status' => null,
        'condition' => null,
        'visible' => null,
        'available_for_view' => null,
        'available_for_sale' => null,
        'is_virtual' => null,
        'in_stock' => null,
        'type' => null,
        'downloadable' => null,
        'weight' => null,
        'length' => null,
        'width' => null,
        'height' => null,
        'weight_unit' => null,
        'dimensions_unit' => null,
        'store_id' => null,
        'lang_id' => null,
        'category_id' => null,
        'warehouse_id' => null,
        'categories_ids' => null,
        'related_products_ids' => null,
        'up_sell_products_ids' => null,
        'cross_sell_products_ids' => null,
        'stores_ids' => null,
        'tax_class_id' => null,
        'meta_title' => null,
        'meta_description' => null,
        'meta_keywords' => null,
        'search_keywords' => null,
        'harmonized_system_code' => null,
        'url' => null,
        'seo_url' => null,
        'manufacturer' => null,
        'manufacturer_id' => null,
        'backorder_status' => null,
        'images' => null,
        'tags' => null,
        'files' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'description' => false,
        'short_description' => false,
        'sku' => false,
        'model' => false,
        'asin' => false,
        'upc' => false,
        'ean' => false,
        'gtin' => false,
        'mpn' => false,
        'barcode' => false,
        'price' => false,
        'old_price' => false,
        'cost_price' => false,
        'special_price' => false,
        'sprice_create' => false,
        'sprice_expire' => false,
        'advanced_prices' => false,
        'fixed_cost_shipping_price' => false,
        'quantity' => false,
        'manage_stock' => false,
        'product_type' => false,
        'marketplace_item_properties' => false,
        'is_free_shipping' => false,
        'taxable' => false,
        'status' => false,
        'condition' => false,
        'visible' => false,
        'available_for_view' => false,
        'available_for_sale' => false,
        'is_virtual' => false,
        'in_stock' => false,
        'type' => false,
        'downloadable' => false,
        'weight' => false,
        'length' => false,
        'width' => false,
        'height' => false,
        'weight_unit' => false,
        'dimensions_unit' => false,
        'store_id' => false,
        'lang_id' => false,
        'category_id' => false,
        'warehouse_id' => false,
        'categories_ids' => false,
        'related_products_ids' => false,
        'up_sell_products_ids' => false,
        'cross_sell_products_ids' => false,
        'stores_ids' => false,
        'tax_class_id' => false,
        'meta_title' => false,
        'meta_description' => false,
        'meta_keywords' => false,
        'search_keywords' => false,
        'harmonized_system_code' => false,
        'url' => false,
        'seo_url' => false,
        'manufacturer' => false,
        'manufacturer_id' => false,
        'backorder_status' => false,
        'images' => false,
        'tags' => false,
        'files' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'description' => 'description',
        'short_description' => 'short_description',
        'sku' => 'sku',
        'model' => 'model',
        'asin' => 'asin',
        'upc' => 'upc',
        'ean' => 'ean',
        'gtin' => 'gtin',
        'mpn' => 'mpn',
        'barcode' => 'barcode',
        'price' => 'price',
        'old_price' => 'old_price',
        'cost_price' => 'cost_price',
        'special_price' => 'special_price',
        'sprice_create' => 'sprice_create',
        'sprice_expire' => 'sprice_expire',
        'advanced_prices' => 'advanced_prices',
        'fixed_cost_shipping_price' => 'fixed_cost_shipping_price',
        'quantity' => 'quantity',
        'manage_stock' => 'manage_stock',
        'product_type' => 'product_type',
        'marketplace_item_properties' => 'marketplace_item_properties',
        'is_free_shipping' => 'is_free_shipping',
        'taxable' => 'taxable',
        'status' => 'status',
        'condition' => 'condition',
        'visible' => 'visible',
        'available_for_view' => 'available_for_view',
        'available_for_sale' => 'available_for_sale',
        'is_virtual' => 'is_virtual',
        'in_stock' => 'in_stock',
        'type' => 'type',
        'downloadable' => 'downloadable',
        'weight' => 'weight',
        'length' => 'length',
        'width' => 'width',
        'height' => 'height',
        'weight_unit' => 'weight_unit',
        'dimensions_unit' => 'dimensions_unit',
        'store_id' => 'store_id',
        'lang_id' => 'lang_id',
        'category_id' => 'category_id',
        'warehouse_id' => 'warehouse_id',
        'categories_ids' => 'categories_ids',
        'related_products_ids' => 'related_products_ids',
        'up_sell_products_ids' => 'up_sell_products_ids',
        'cross_sell_products_ids' => 'cross_sell_products_ids',
        'stores_ids' => 'stores_ids',
        'tax_class_id' => 'tax_class_id',
        'meta_title' => 'meta_title',
        'meta_description' => 'meta_description',
        'meta_keywords' => 'meta_keywords',
        'search_keywords' => 'search_keywords',
        'harmonized_system_code' => 'harmonized_system_code',
        'url' => 'url',
        'seo_url' => 'seo_url',
        'manufacturer' => 'manufacturer',
        'manufacturer_id' => 'manufacturer_id',
        'backorder_status' => 'backorder_status',
        'images' => 'images',
        'tags' => 'tags',
        'files' => 'files'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'description' => 'setDescription',
        'short_description' => 'setShortDescription',
        'sku' => 'setSku',
        'model' => 'setModel',
        'asin' => 'setAsin',
        'upc' => 'setUpc',
        'ean' => 'setEan',
        'gtin' => 'setGtin',
        'mpn' => 'setMpn',
        'barcode' => 'setBarcode',
        'price' => 'setPrice',
        'old_price' => 'setOldPrice',
        'cost_price' => 'setCostPrice',
        'special_price' => 'setSpecialPrice',
        'sprice_create' => 'setSpriceCreate',
        'sprice_expire' => 'setSpriceExpire',
        'advanced_prices' => 'setAdvancedPrices',
        'fixed_cost_shipping_price' => 'setFixedCostShippingPrice',
        'quantity' => 'setQuantity',
        'manage_stock' => 'setManageStock',
        'product_type' => 'setProductType',
        'marketplace_item_properties' => 'setMarketplaceItemProperties',
        'is_free_shipping' => 'setIsFreeShipping',
        'taxable' => 'setTaxable',
        'status' => 'setStatus',
        'condition' => 'setCondition',
        'visible' => 'setVisible',
        'available_for_view' => 'setAvailableForView',
        'available_for_sale' => 'setAvailableForSale',
        'is_virtual' => 'setIsVirtual',
        'in_stock' => 'setInStock',
        'type' => 'setType',
        'downloadable' => 'setDownloadable',
        'weight' => 'setWeight',
        'length' => 'setLength',
        'width' => 'setWidth',
        'height' => 'setHeight',
        'weight_unit' => 'setWeightUnit',
        'dimensions_unit' => 'setDimensionsUnit',
        'store_id' => 'setStoreId',
        'lang_id' => 'setLangId',
        'category_id' => 'setCategoryId',
        'warehouse_id' => 'setWarehouseId',
        'categories_ids' => 'setCategoriesIds',
        'related_products_ids' => 'setRelatedProductsIds',
        'up_sell_products_ids' => 'setUpSellProductsIds',
        'cross_sell_products_ids' => 'setCrossSellProductsIds',
        'stores_ids' => 'setStoresIds',
        'tax_class_id' => 'setTaxClassId',
        'meta_title' => 'setMetaTitle',
        'meta_description' => 'setMetaDescription',
        'meta_keywords' => 'setMetaKeywords',
        'search_keywords' => 'setSearchKeywords',
        'harmonized_system_code' => 'setHarmonizedSystemCode',
        'url' => 'setUrl',
        'seo_url' => 'setSeoUrl',
        'manufacturer' => 'setManufacturer',
        'manufacturer_id' => 'setManufacturerId',
        'backorder_status' => 'setBackorderStatus',
        'images' => 'setImages',
        'tags' => 'setTags',
        'files' => 'setFiles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'description' => 'getDescription',
        'short_description' => 'getShortDescription',
        'sku' => 'getSku',
        'model' => 'getModel',
        'asin' => 'getAsin',
        'upc' => 'getUpc',
        'ean' => 'getEan',
        'gtin' => 'getGtin',
        'mpn' => 'getMpn',
        'barcode' => 'getBarcode',
        'price' => 'getPrice',
        'old_price' => 'getOldPrice',
        'cost_price' => 'getCostPrice',
        'special_price' => 'getSpecialPrice',
        'sprice_create' => 'getSpriceCreate',
        'sprice_expire' => 'getSpriceExpire',
        'advanced_prices' => 'getAdvancedPrices',
        'fixed_cost_shipping_price' => 'getFixedCostShippingPrice',
        'quantity' => 'getQuantity',
        'manage_stock' => 'getManageStock',
        'product_type' => 'getProductType',
        'marketplace_item_properties' => 'getMarketplaceItemProperties',
        'is_free_shipping' => 'getIsFreeShipping',
        'taxable' => 'getTaxable',
        'status' => 'getStatus',
        'condition' => 'getCondition',
        'visible' => 'getVisible',
        'available_for_view' => 'getAvailableForView',
        'available_for_sale' => 'getAvailableForSale',
        'is_virtual' => 'getIsVirtual',
        'in_stock' => 'getInStock',
        'type' => 'getType',
        'downloadable' => 'getDownloadable',
        'weight' => 'getWeight',
        'length' => 'getLength',
        'width' => 'getWidth',
        'height' => 'getHeight',
        'weight_unit' => 'getWeightUnit',
        'dimensions_unit' => 'getDimensionsUnit',
        'store_id' => 'getStoreId',
        'lang_id' => 'getLangId',
        'category_id' => 'getCategoryId',
        'warehouse_id' => 'getWarehouseId',
        'categories_ids' => 'getCategoriesIds',
        'related_products_ids' => 'getRelatedProductsIds',
        'up_sell_products_ids' => 'getUpSellProductsIds',
        'cross_sell_products_ids' => 'getCrossSellProductsIds',
        'stores_ids' => 'getStoresIds',
        'tax_class_id' => 'getTaxClassId',
        'meta_title' => 'getMetaTitle',
        'meta_description' => 'getMetaDescription',
        'meta_keywords' => 'getMetaKeywords',
        'search_keywords' => 'getSearchKeywords',
        'harmonized_system_code' => 'getHarmonizedSystemCode',
        'url' => 'getUrl',
        'seo_url' => 'getSeoUrl',
        'manufacturer' => 'getManufacturer',
        'manufacturer_id' => 'getManufacturerId',
        'backorder_status' => 'getBackorderStatus',
        'images' => 'getImages',
        'tags' => 'getTags',
        'files' => 'getFiles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('short_description', $data ?? [], null);
        $this->setIfExists('sku', $data ?? [], null);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('asin', $data ?? [], null);
        $this->setIfExists('upc', $data ?? [], null);
        $this->setIfExists('ean', $data ?? [], null);
        $this->setIfExists('gtin', $data ?? [], null);
        $this->setIfExists('mpn', $data ?? [], null);
        $this->setIfExists('barcode', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('old_price', $data ?? [], null);
        $this->setIfExists('cost_price', $data ?? [], null);
        $this->setIfExists('special_price', $data ?? [], null);
        $this->setIfExists('sprice_create', $data ?? [], null);
        $this->setIfExists('sprice_expire', $data ?? [], null);
        $this->setIfExists('advanced_prices', $data ?? [], null);
        $this->setIfExists('fixed_cost_shipping_price', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('manage_stock', $data ?? [], null);
        $this->setIfExists('product_type', $data ?? [], null);
        $this->setIfExists('marketplace_item_properties', $data ?? [], null);
        $this->setIfExists('is_free_shipping', $data ?? [], null);
        $this->setIfExists('taxable', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('condition', $data ?? [], null);
        $this->setIfExists('visible', $data ?? [], null);
        $this->setIfExists('available_for_view', $data ?? [], null);
        $this->setIfExists('available_for_sale', $data ?? [], null);
        $this->setIfExists('is_virtual', $data ?? [], null);
        $this->setIfExists('in_stock', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('downloadable', $data ?? [], null);
        $this->setIfExists('weight', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('weight_unit', $data ?? [], null);
        $this->setIfExists('dimensions_unit', $data ?? [], null);
        $this->setIfExists('store_id', $data ?? [], null);
        $this->setIfExists('lang_id', $data ?? [], null);
        $this->setIfExists('category_id', $data ?? [], null);
        $this->setIfExists('warehouse_id', $data ?? [], null);
        $this->setIfExists('categories_ids', $data ?? [], null);
        $this->setIfExists('related_products_ids', $data ?? [], null);
        $this->setIfExists('up_sell_products_ids', $data ?? [], null);
        $this->setIfExists('cross_sell_products_ids', $data ?? [], null);
        $this->setIfExists('stores_ids', $data ?? [], null);
        $this->setIfExists('tax_class_id', $data ?? [], null);
        $this->setIfExists('meta_title', $data ?? [], null);
        $this->setIfExists('meta_description', $data ?? [], null);
        $this->setIfExists('meta_keywords', $data ?? [], null);
        $this->setIfExists('search_keywords', $data ?? [], null);
        $this->setIfExists('harmonized_system_code', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('seo_url', $data ?? [], null);
        $this->setIfExists('manufacturer', $data ?? [], null);
        $this->setIfExists('manufacturer_id', $data ?? [], null);
        $this->setIfExists('backorder_status', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('files', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['categories_ids']) && (count($this->container['categories_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'categories_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['related_products_ids']) && (count($this->container['related_products_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'related_products_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['up_sell_products_ids']) && (count($this->container['up_sell_products_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'up_sell_products_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['cross_sell_products_ids']) && (count($this->container['cross_sell_products_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'cross_sell_products_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['stores_ids']) && (count($this->container['stores_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'stores_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['meta_keywords']) && (count($this->container['meta_keywords']) < 1)) {
            $invalidProperties[] = "invalid value for 'meta_keywords', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['search_keywords']) && (count($this->container['search_keywords']) < 1)) {
            $invalidProperties[] = "invalid value for 'search_keywords', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['images']) && (count($this->container['images']) < 1)) {
            $invalidProperties[] = "invalid value for 'images', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['tags']) && (count($this->container['tags']) < 1)) {
            $invalidProperties[] = "invalid value for 'tags', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['files']) && (count($this->container['files']) < 1)) {
            $invalidProperties[] = "invalid value for 'files', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets short_description
     *
     * @return string|null
     */
    public function getShortDescription()
    {
        return $this->container['short_description'];
    }

    /**
     * Sets short_description
     *
     * @param string|null $short_description short_description
     *
     * @return self
     */
    public function setShortDescription($short_description)
    {
        if (is_null($short_description)) {
            throw new \InvalidArgumentException('non-nullable short_description cannot be null');
        }
        $this->container['short_description'] = $short_description;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string|null
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string|null $sku sku
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string|null $model model
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            throw new \InvalidArgumentException('non-nullable model cannot be null');
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets asin
     *
     * @return string|null
     */
    public function getAsin()
    {
        return $this->container['asin'];
    }

    /**
     * Sets asin
     *
     * @param string|null $asin asin
     *
     * @return self
     */
    public function setAsin($asin)
    {
        if (is_null($asin)) {
            throw new \InvalidArgumentException('non-nullable asin cannot be null');
        }
        $this->container['asin'] = $asin;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string|null
     */
    public function getUpc()
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string|null $upc upc
     *
     * @return self
     */
    public function setUpc($upc)
    {
        if (is_null($upc)) {
            throw new \InvalidArgumentException('non-nullable upc cannot be null');
        }
        $this->container['upc'] = $upc;

        return $this;
    }

    /**
     * Gets ean
     *
     * @return string|null
     */
    public function getEan()
    {
        return $this->container['ean'];
    }

    /**
     * Sets ean
     *
     * @param string|null $ean ean
     *
     * @return self
     */
    public function setEan($ean)
    {
        if (is_null($ean)) {
            throw new \InvalidArgumentException('non-nullable ean cannot be null');
        }
        $this->container['ean'] = $ean;

        return $this;
    }

    /**
     * Gets gtin
     *
     * @return string|null
     */
    public function getGtin()
    {
        return $this->container['gtin'];
    }

    /**
     * Sets gtin
     *
     * @param string|null $gtin gtin
     *
     * @return self
     */
    public function setGtin($gtin)
    {
        if (is_null($gtin)) {
            throw new \InvalidArgumentException('non-nullable gtin cannot be null');
        }
        $this->container['gtin'] = $gtin;

        return $this;
    }

    /**
     * Gets mpn
     *
     * @return string|null
     */
    public function getMpn()
    {
        return $this->container['mpn'];
    }

    /**
     * Sets mpn
     *
     * @param string|null $mpn mpn
     *
     * @return self
     */
    public function setMpn($mpn)
    {
        if (is_null($mpn)) {
            throw new \InvalidArgumentException('non-nullable mpn cannot be null');
        }
        $this->container['mpn'] = $mpn;

        return $this;
    }

    /**
     * Gets barcode
     *
     * @return string|null
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     *
     * @param string|null $barcode barcode
     *
     * @return self
     */
    public function setBarcode($barcode)
    {
        if (is_null($barcode)) {
            throw new \InvalidArgumentException('non-nullable barcode cannot be null');
        }
        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets old_price
     *
     * @return float|null
     */
    public function getOldPrice()
    {
        return $this->container['old_price'];
    }

    /**
     * Sets old_price
     *
     * @param float|null $old_price old_price
     *
     * @return self
     */
    public function setOldPrice($old_price)
    {
        if (is_null($old_price)) {
            throw new \InvalidArgumentException('non-nullable old_price cannot be null');
        }
        $this->container['old_price'] = $old_price;

        return $this;
    }

    /**
     * Gets cost_price
     *
     * @return float|null
     */
    public function getCostPrice()
    {
        return $this->container['cost_price'];
    }

    /**
     * Sets cost_price
     *
     * @param float|null $cost_price cost_price
     *
     * @return self
     */
    public function setCostPrice($cost_price)
    {
        if (is_null($cost_price)) {
            throw new \InvalidArgumentException('non-nullable cost_price cannot be null');
        }
        $this->container['cost_price'] = $cost_price;

        return $this;
    }

    /**
     * Gets special_price
     *
     * @return float|null
     */
    public function getSpecialPrice()
    {
        return $this->container['special_price'];
    }

    /**
     * Sets special_price
     *
     * @param float|null $special_price special_price
     *
     * @return self
     */
    public function setSpecialPrice($special_price)
    {
        if (is_null($special_price)) {
            throw new \InvalidArgumentException('non-nullable special_price cannot be null');
        }
        $this->container['special_price'] = $special_price;

        return $this;
    }

    /**
     * Gets sprice_create
     *
     * @return string|null
     */
    public function getSpriceCreate()
    {
        return $this->container['sprice_create'];
    }

    /**
     * Sets sprice_create
     *
     * @param string|null $sprice_create sprice_create
     *
     * @return self
     */
    public function setSpriceCreate($sprice_create)
    {
        if (is_null($sprice_create)) {
            throw new \InvalidArgumentException('non-nullable sprice_create cannot be null');
        }
        $this->container['sprice_create'] = $sprice_create;

        return $this;
    }

    /**
     * Gets sprice_expire
     *
     * @return string|null
     */
    public function getSpriceExpire()
    {
        return $this->container['sprice_expire'];
    }

    /**
     * Sets sprice_expire
     *
     * @param string|null $sprice_expire sprice_expire
     *
     * @return self
     */
    public function setSpriceExpire($sprice_expire)
    {
        if (is_null($sprice_expire)) {
            throw new \InvalidArgumentException('non-nullable sprice_expire cannot be null');
        }
        $this->container['sprice_expire'] = $sprice_expire;

        return $this;
    }

    /**
     * Gets advanced_prices
     *
     * @return \OpenAPI\Client\Model\ProductAddBatchPayloadInnerAdvancedPricesInner[]|null
     */
    public function getAdvancedPrices()
    {
        return $this->container['advanced_prices'];
    }

    /**
     * Sets advanced_prices
     *
     * @param \OpenAPI\Client\Model\ProductAddBatchPayloadInnerAdvancedPricesInner[]|null $advanced_prices advanced_prices
     *
     * @return self
     */
    public function setAdvancedPrices($advanced_prices)
    {
        if (is_null($advanced_prices)) {
            throw new \InvalidArgumentException('non-nullable advanced_prices cannot be null');
        }
        $this->container['advanced_prices'] = $advanced_prices;

        return $this;
    }

    /**
     * Gets fixed_cost_shipping_price
     *
     * @return float|null
     */
    public function getFixedCostShippingPrice()
    {
        return $this->container['fixed_cost_shipping_price'];
    }

    /**
     * Sets fixed_cost_shipping_price
     *
     * @param float|null $fixed_cost_shipping_price fixed_cost_shipping_price
     *
     * @return self
     */
    public function setFixedCostShippingPrice($fixed_cost_shipping_price)
    {
        if (is_null($fixed_cost_shipping_price)) {
            throw new \InvalidArgumentException('non-nullable fixed_cost_shipping_price cannot be null');
        }
        $this->container['fixed_cost_shipping_price'] = $fixed_cost_shipping_price;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets manage_stock
     *
     * @return bool|null
     */
    public function getManageStock()
    {
        return $this->container['manage_stock'];
    }

    /**
     * Sets manage_stock
     *
     * @param bool|null $manage_stock manage_stock
     *
     * @return self
     */
    public function setManageStock($manage_stock)
    {
        if (is_null($manage_stock)) {
            throw new \InvalidArgumentException('non-nullable manage_stock cannot be null');
        }
        $this->container['manage_stock'] = $manage_stock;

        return $this;
    }

    /**
     * Gets product_type
     *
     * @return string|null
     */
    public function getProductType()
    {
        return $this->container['product_type'];
    }

    /**
     * Sets product_type
     *
     * @param string|null $product_type product_type
     *
     * @return self
     */
    public function setProductType($product_type)
    {
        if (is_null($product_type)) {
            throw new \InvalidArgumentException('non-nullable product_type cannot be null');
        }
        $this->container['product_type'] = $product_type;

        return $this;
    }

    /**
     * Gets marketplace_item_properties
     *
     * @return object|null
     */
    public function getMarketplaceItemProperties()
    {
        return $this->container['marketplace_item_properties'];
    }

    /**
     * Sets marketplace_item_properties
     *
     * @param object|null $marketplace_item_properties marketplace_item_properties
     *
     * @return self
     */
    public function setMarketplaceItemProperties($marketplace_item_properties)
    {
        if (is_null($marketplace_item_properties)) {
            throw new \InvalidArgumentException('non-nullable marketplace_item_properties cannot be null');
        }
        $this->container['marketplace_item_properties'] = $marketplace_item_properties;

        return $this;
    }

    /**
     * Gets is_free_shipping
     *
     * @return bool|null
     */
    public function getIsFreeShipping()
    {
        return $this->container['is_free_shipping'];
    }

    /**
     * Sets is_free_shipping
     *
     * @param bool|null $is_free_shipping is_free_shipping
     *
     * @return self
     */
    public function setIsFreeShipping($is_free_shipping)
    {
        if (is_null($is_free_shipping)) {
            throw new \InvalidArgumentException('non-nullable is_free_shipping cannot be null');
        }
        $this->container['is_free_shipping'] = $is_free_shipping;

        return $this;
    }

    /**
     * Gets taxable
     *
     * @return bool|null
     */
    public function getTaxable()
    {
        return $this->container['taxable'];
    }

    /**
     * Sets taxable
     *
     * @param bool|null $taxable taxable
     *
     * @return self
     */
    public function setTaxable($taxable)
    {
        if (is_null($taxable)) {
            throw new \InvalidArgumentException('non-nullable taxable cannot be null');
        }
        $this->container['taxable'] = $taxable;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return string|null
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param string|null $condition condition
     *
     * @return self
     */
    public function setCondition($condition)
    {
        if (is_null($condition)) {
            throw new \InvalidArgumentException('non-nullable condition cannot be null');
        }
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets visible
     *
     * @return string|null
     */
    public function getVisible()
    {
        return $this->container['visible'];
    }

    /**
     * Sets visible
     *
     * @param string|null $visible visible
     *
     * @return self
     */
    public function setVisible($visible)
    {
        if (is_null($visible)) {
            throw new \InvalidArgumentException('non-nullable visible cannot be null');
        }
        $this->container['visible'] = $visible;

        return $this;
    }

    /**
     * Gets available_for_view
     *
     * @return bool|null
     */
    public function getAvailableForView()
    {
        return $this->container['available_for_view'];
    }

    /**
     * Sets available_for_view
     *
     * @param bool|null $available_for_view available_for_view
     *
     * @return self
     */
    public function setAvailableForView($available_for_view)
    {
        if (is_null($available_for_view)) {
            throw new \InvalidArgumentException('non-nullable available_for_view cannot be null');
        }
        $this->container['available_for_view'] = $available_for_view;

        return $this;
    }

    /**
     * Gets available_for_sale
     *
     * @return bool|null
     */
    public function getAvailableForSale()
    {
        return $this->container['available_for_sale'];
    }

    /**
     * Sets available_for_sale
     *
     * @param bool|null $available_for_sale available_for_sale
     *
     * @return self
     */
    public function setAvailableForSale($available_for_sale)
    {
        if (is_null($available_for_sale)) {
            throw new \InvalidArgumentException('non-nullable available_for_sale cannot be null');
        }
        $this->container['available_for_sale'] = $available_for_sale;

        return $this;
    }

    /**
     * Gets is_virtual
     *
     * @return bool|null
     */
    public function getIsVirtual()
    {
        return $this->container['is_virtual'];
    }

    /**
     * Sets is_virtual
     *
     * @param bool|null $is_virtual is_virtual
     *
     * @return self
     */
    public function setIsVirtual($is_virtual)
    {
        if (is_null($is_virtual)) {
            throw new \InvalidArgumentException('non-nullable is_virtual cannot be null');
        }
        $this->container['is_virtual'] = $is_virtual;

        return $this;
    }

    /**
     * Gets in_stock
     *
     * @return bool|null
     */
    public function getInStock()
    {
        return $this->container['in_stock'];
    }

    /**
     * Sets in_stock
     *
     * @param bool|null $in_stock in_stock
     *
     * @return self
     */
    public function setInStock($in_stock)
    {
        if (is_null($in_stock)) {
            throw new \InvalidArgumentException('non-nullable in_stock cannot be null');
        }
        $this->container['in_stock'] = $in_stock;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets downloadable
     *
     * @return bool|null
     */
    public function getDownloadable()
    {
        return $this->container['downloadable'];
    }

    /**
     * Sets downloadable
     *
     * @param bool|null $downloadable downloadable
     *
     * @return self
     */
    public function setDownloadable($downloadable)
    {
        if (is_null($downloadable)) {
            throw new \InvalidArgumentException('non-nullable downloadable cannot be null');
        }
        $this->container['downloadable'] = $downloadable;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return float|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param float|null $weight weight
     *
     * @return self
     */
    public function setWeight($weight)
    {
        if (is_null($weight)) {
            throw new \InvalidArgumentException('non-nullable weight cannot be null');
        }
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets length
     *
     * @return float|null
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param float|null $length length
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets width
     *
     * @return float|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param float|null $width width
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            throw new \InvalidArgumentException('non-nullable width cannot be null');
        }
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return float|null
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param float|null $height height
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            throw new \InvalidArgumentException('non-nullable height cannot be null');
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets weight_unit
     *
     * @return string|null
     */
    public function getWeightUnit()
    {
        return $this->container['weight_unit'];
    }

    /**
     * Sets weight_unit
     *
     * @param string|null $weight_unit weight_unit
     *
     * @return self
     */
    public function setWeightUnit($weight_unit)
    {
        if (is_null($weight_unit)) {
            throw new \InvalidArgumentException('non-nullable weight_unit cannot be null');
        }
        $this->container['weight_unit'] = $weight_unit;

        return $this;
    }

    /**
     * Gets dimensions_unit
     *
     * @return string|null
     */
    public function getDimensionsUnit()
    {
        return $this->container['dimensions_unit'];
    }

    /**
     * Sets dimensions_unit
     *
     * @param string|null $dimensions_unit dimensions_unit
     *
     * @return self
     */
    public function setDimensionsUnit($dimensions_unit)
    {
        if (is_null($dimensions_unit)) {
            throw new \InvalidArgumentException('non-nullable dimensions_unit cannot be null');
        }
        $this->container['dimensions_unit'] = $dimensions_unit;

        return $this;
    }

    /**
     * Gets store_id
     *
     * @return string|null
     */
    public function getStoreId()
    {
        return $this->container['store_id'];
    }

    /**
     * Sets store_id
     *
     * @param string|null $store_id store_id
     *
     * @return self
     */
    public function setStoreId($store_id)
    {
        if (is_null($store_id)) {
            throw new \InvalidArgumentException('non-nullable store_id cannot be null');
        }
        $this->container['store_id'] = $store_id;

        return $this;
    }

    /**
     * Gets lang_id
     *
     * @return string|null
     */
    public function getLangId()
    {
        return $this->container['lang_id'];
    }

    /**
     * Sets lang_id
     *
     * @param string|null $lang_id lang_id
     *
     * @return self
     */
    public function setLangId($lang_id)
    {
        if (is_null($lang_id)) {
            throw new \InvalidArgumentException('non-nullable lang_id cannot be null');
        }
        $this->container['lang_id'] = $lang_id;

        return $this;
    }

    /**
     * Gets category_id
     *
     * @return string|null
     */
    public function getCategoryId()
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     *
     * @param string|null $category_id category_id
     *
     * @return self
     */
    public function setCategoryId($category_id)
    {
        if (is_null($category_id)) {
            throw new \InvalidArgumentException('non-nullable category_id cannot be null');
        }
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets warehouse_id
     *
     * @return string|null
     */
    public function getWarehouseId()
    {
        return $this->container['warehouse_id'];
    }

    /**
     * Sets warehouse_id
     *
     * @param string|null $warehouse_id warehouse_id
     *
     * @return self
     */
    public function setWarehouseId($warehouse_id)
    {
        if (is_null($warehouse_id)) {
            throw new \InvalidArgumentException('non-nullable warehouse_id cannot be null');
        }
        $this->container['warehouse_id'] = $warehouse_id;

        return $this;
    }

    /**
     * Gets categories_ids
     *
     * @return string[]|null
     */
    public function getCategoriesIds()
    {
        return $this->container['categories_ids'];
    }

    /**
     * Sets categories_ids
     *
     * @param string[]|null $categories_ids categories_ids
     *
     * @return self
     */
    public function setCategoriesIds($categories_ids)
    {
        if (is_null($categories_ids)) {
            throw new \InvalidArgumentException('non-nullable categories_ids cannot be null');
        }


        if ((count($categories_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $categories_ids when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['categories_ids'] = $categories_ids;

        return $this;
    }

    /**
     * Gets related_products_ids
     *
     * @return string[]|null
     */
    public function getRelatedProductsIds()
    {
        return $this->container['related_products_ids'];
    }

    /**
     * Sets related_products_ids
     *
     * @param string[]|null $related_products_ids related_products_ids
     *
     * @return self
     */
    public function setRelatedProductsIds($related_products_ids)
    {
        if (is_null($related_products_ids)) {
            throw new \InvalidArgumentException('non-nullable related_products_ids cannot be null');
        }


        if ((count($related_products_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $related_products_ids when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['related_products_ids'] = $related_products_ids;

        return $this;
    }

    /**
     * Gets up_sell_products_ids
     *
     * @return string[]|null
     */
    public function getUpSellProductsIds()
    {
        return $this->container['up_sell_products_ids'];
    }

    /**
     * Sets up_sell_products_ids
     *
     * @param string[]|null $up_sell_products_ids up_sell_products_ids
     *
     * @return self
     */
    public function setUpSellProductsIds($up_sell_products_ids)
    {
        if (is_null($up_sell_products_ids)) {
            throw new \InvalidArgumentException('non-nullable up_sell_products_ids cannot be null');
        }


        if ((count($up_sell_products_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $up_sell_products_ids when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['up_sell_products_ids'] = $up_sell_products_ids;

        return $this;
    }

    /**
     * Gets cross_sell_products_ids
     *
     * @return string[]|null
     */
    public function getCrossSellProductsIds()
    {
        return $this->container['cross_sell_products_ids'];
    }

    /**
     * Sets cross_sell_products_ids
     *
     * @param string[]|null $cross_sell_products_ids cross_sell_products_ids
     *
     * @return self
     */
    public function setCrossSellProductsIds($cross_sell_products_ids)
    {
        if (is_null($cross_sell_products_ids)) {
            throw new \InvalidArgumentException('non-nullable cross_sell_products_ids cannot be null');
        }


        if ((count($cross_sell_products_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $cross_sell_products_ids when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['cross_sell_products_ids'] = $cross_sell_products_ids;

        return $this;
    }

    /**
     * Gets stores_ids
     *
     * @return string[]|null
     */
    public function getStoresIds()
    {
        return $this->container['stores_ids'];
    }

    /**
     * Sets stores_ids
     *
     * @param string[]|null $stores_ids stores_ids
     *
     * @return self
     */
    public function setStoresIds($stores_ids)
    {
        if (is_null($stores_ids)) {
            throw new \InvalidArgumentException('non-nullable stores_ids cannot be null');
        }


        if ((count($stores_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $stores_ids when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['stores_ids'] = $stores_ids;

        return $this;
    }

    /**
     * Gets tax_class_id
     *
     * @return string|null
     */
    public function getTaxClassId()
    {
        return $this->container['tax_class_id'];
    }

    /**
     * Sets tax_class_id
     *
     * @param string|null $tax_class_id tax_class_id
     *
     * @return self
     */
    public function setTaxClassId($tax_class_id)
    {
        if (is_null($tax_class_id)) {
            throw new \InvalidArgumentException('non-nullable tax_class_id cannot be null');
        }
        $this->container['tax_class_id'] = $tax_class_id;

        return $this;
    }

    /**
     * Gets meta_title
     *
     * @return string|null
     */
    public function getMetaTitle()
    {
        return $this->container['meta_title'];
    }

    /**
     * Sets meta_title
     *
     * @param string|null $meta_title meta_title
     *
     * @return self
     */
    public function setMetaTitle($meta_title)
    {
        if (is_null($meta_title)) {
            throw new \InvalidArgumentException('non-nullable meta_title cannot be null');
        }
        $this->container['meta_title'] = $meta_title;

        return $this;
    }

    /**
     * Gets meta_description
     *
     * @return string|null
     */
    public function getMetaDescription()
    {
        return $this->container['meta_description'];
    }

    /**
     * Sets meta_description
     *
     * @param string|null $meta_description meta_description
     *
     * @return self
     */
    public function setMetaDescription($meta_description)
    {
        if (is_null($meta_description)) {
            throw new \InvalidArgumentException('non-nullable meta_description cannot be null');
        }
        $this->container['meta_description'] = $meta_description;

        return $this;
    }

    /**
     * Gets meta_keywords
     *
     * @return string[]|null
     */
    public function getMetaKeywords()
    {
        return $this->container['meta_keywords'];
    }

    /**
     * Sets meta_keywords
     *
     * @param string[]|null $meta_keywords meta_keywords
     *
     * @return self
     */
    public function setMetaKeywords($meta_keywords)
    {
        if (is_null($meta_keywords)) {
            throw new \InvalidArgumentException('non-nullable meta_keywords cannot be null');
        }


        if ((count($meta_keywords) < 1)) {
            throw new \InvalidArgumentException('invalid length for $meta_keywords when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['meta_keywords'] = $meta_keywords;

        return $this;
    }

    /**
     * Gets search_keywords
     *
     * @return string[]|null
     */
    public function getSearchKeywords()
    {
        return $this->container['search_keywords'];
    }

    /**
     * Sets search_keywords
     *
     * @param string[]|null $search_keywords search_keywords
     *
     * @return self
     */
    public function setSearchKeywords($search_keywords)
    {
        if (is_null($search_keywords)) {
            throw new \InvalidArgumentException('non-nullable search_keywords cannot be null');
        }


        if ((count($search_keywords) < 1)) {
            throw new \InvalidArgumentException('invalid length for $search_keywords when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['search_keywords'] = $search_keywords;

        return $this;
    }

    /**
     * Gets harmonized_system_code
     *
     * @return string|null
     */
    public function getHarmonizedSystemCode()
    {
        return $this->container['harmonized_system_code'];
    }

    /**
     * Sets harmonized_system_code
     *
     * @param string|null $harmonized_system_code harmonized_system_code
     *
     * @return self
     */
    public function setHarmonizedSystemCode($harmonized_system_code)
    {
        if (is_null($harmonized_system_code)) {
            throw new \InvalidArgumentException('non-nullable harmonized_system_code cannot be null');
        }
        $this->container['harmonized_system_code'] = $harmonized_system_code;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets seo_url
     *
     * @return string|null
     */
    public function getSeoUrl()
    {
        return $this->container['seo_url'];
    }

    /**
     * Sets seo_url
     *
     * @param string|null $seo_url seo_url
     *
     * @return self
     */
    public function setSeoUrl($seo_url)
    {
        if (is_null($seo_url)) {
            throw new \InvalidArgumentException('non-nullable seo_url cannot be null');
        }
        $this->container['seo_url'] = $seo_url;

        return $this;
    }

    /**
     * Gets manufacturer
     *
     * @return string|null
     */
    public function getManufacturer()
    {
        return $this->container['manufacturer'];
    }

    /**
     * Sets manufacturer
     *
     * @param string|null $manufacturer manufacturer
     *
     * @return self
     */
    public function setManufacturer($manufacturer)
    {
        if (is_null($manufacturer)) {
            throw new \InvalidArgumentException('non-nullable manufacturer cannot be null');
        }
        $this->container['manufacturer'] = $manufacturer;

        return $this;
    }

    /**
     * Gets manufacturer_id
     *
     * @return string|null
     */
    public function getManufacturerId()
    {
        return $this->container['manufacturer_id'];
    }

    /**
     * Sets manufacturer_id
     *
     * @param string|null $manufacturer_id manufacturer_id
     *
     * @return self
     */
    public function setManufacturerId($manufacturer_id)
    {
        if (is_null($manufacturer_id)) {
            throw new \InvalidArgumentException('non-nullable manufacturer_id cannot be null');
        }
        $this->container['manufacturer_id'] = $manufacturer_id;

        return $this;
    }

    /**
     * Gets backorder_status
     *
     * @return string|null
     */
    public function getBackorderStatus()
    {
        return $this->container['backorder_status'];
    }

    /**
     * Sets backorder_status
     *
     * @param string|null $backorder_status backorder_status
     *
     * @return self
     */
    public function setBackorderStatus($backorder_status)
    {
        if (is_null($backorder_status)) {
            throw new \InvalidArgumentException('non-nullable backorder_status cannot be null');
        }
        $this->container['backorder_status'] = $backorder_status;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \OpenAPI\Client\Model\ProductAddBatchPayloadInnerImagesInner[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \OpenAPI\Client\Model\ProductAddBatchPayloadInnerImagesInner[]|null $images images
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }


        if ((count($images) < 1)) {
            throw new \InvalidArgumentException('invalid length for $images when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }


        if ((count($tags) < 1)) {
            throw new \InvalidArgumentException('invalid length for $tags when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \OpenAPI\Client\Model\ProductAddFilesInner[]|null
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \OpenAPI\Client\Model\ProductAddFilesInner[]|null $files files
     *
     * @return self
     */
    public function setFiles($files)
    {
        if (is_null($files)) {
            throw new \InvalidArgumentException('non-nullable files cannot be null');
        }


        if ((count($files) < 1)) {
            throw new \InvalidArgumentException('invalid length for $files when calling ProductAddBatchPayloadInner., number of items must be greater than or equal to 1.');
        }
        $this->container['files'] = $files;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


